### PR TITLE
Check for connected board before auto-ing

### LINKED ISSUE #1: "Auto" before "Reconnect" causes menu to break
Unity Version: 2021.3.8f1
Brainflow Version: 5.2.0
Release: 0.1.2

Issue:
Threshold bars and sliders appear as 0 and unchanging

Steps to reproduce:
1. Follow installation guide with a new 3D project
2. Press play
3. Press "Auto"
4. Press "Reconnect"

### PR DESCRIPTION
**Pull request by MJE10**

### CODE REVIEW

**Comment by MJE10** [comment]
@Fumpledump check for code style and obvious c# errors, should be fine

**Comment by MJE10** [comment]
#1

**Review by marytheproducer — APPROVED** [review]
That seems good to me as long as you meant for the for loop to not happen anymore

**Comment by MJE10** [comment]
Yeah all good, it was deleted from 326 but added again on 332

**Pull request merged**
